# Generated by Django 5.0.2 on 2024-03-18 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_cities_countries_departments_identification_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811))),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('id_dept', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811))),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811))),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('id_ident_type', models.IntegerField()),
                ('ident_number', models.CharField(blank=True, max_length=15)),
                ('id_exp_city', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=50)),
                ('id_user', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 161819))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 161819))),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 125491))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 125491))),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='departments',
            name='id_country',
        ),
        migrations.DeleteModel(
            name='identification_types',
        ),
        migrations.AlterField(
            model_name='students',
            name='id_person',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='update_at',
        ),
        migrations.AddField(
            model_name='cities',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='id_dept',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 161819)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 162811)),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 29, 50, 161819)),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.DeleteModel(
            name='countries',
        ),
        migrations.DeleteModel(
            name='departments',
        ),
        migrations.DeleteModel(
            name='persons',
        ),
    ]
